language: c

matrix:
  include:
    - os: osx
      osx_image: xcode9.3
      env:
        - MATRIX_EVAL='brew install llvm clinfo; clinfo'
    - os: linux
      compiler: gcc-7
      env:
        - MATRIX_EVAL="export CC='gcc-7'"

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - ocl-icd-opencl-dev

before_script:
  - export CFLAGS='-Werror'
  - eval "${MATRIX_EVAL}"

script:
  - . ci.sh

notifications:
  email: false
